export interface Post {
id: number, 
title: string, 
likes: number,
done?: boolean
}

export type CreateTodoPayload = Omit<Post, "id"> //id is automatically generated by Axios <Which type, what you want to omit>